
<template>
    <div class="navhome">
        <a href="/" class="removelink">
            <div class="navhome__logo--container">
                <img class="navhome__logo--image" src="../../assets/images/cogov__logo--white.png" alt="">
                <p class="navhome__logo--text">CoGov</p>            
            </div>        
        </a>
        <div class="navhome__items">
            <div class="navhome__item">
                <a href='/about' class="removelink">About</a>
            </div>
            <div class="navhome__item">
                <a href='/holochain' class="removelink">Holochain</a>
            </div>
            <div class="navhome__item">
                <a href='/connect' class="removelink">Connect</a>
            </div>
            <button class="navhome__button">   
                Whitepaper
            </button>
        </div>

    </div>
</template>
