
<template>
    <div class="nav">
        <div class="nav__logo--container">
            <img class="nav__logo--image" src="../../assets/images/cogov__logo--purple.png" alt="">
            <p class="nav__logo--text">CoGov</p>
        </div>
        <div class="nav__items">
            <div class="nav__item">Team</div>
            <div class="nav__item">CoGov in Depth</div>
            <div class="nav__item">Holochain</div>
            <div class="nav__item">Whitepaper</div>
            <div class="nav__item">Connect</div>
        </div>

    </div>
</template>
