
<template>
    <div class="nav">
        <a href="/" class="removelink">
            <div class="nav__logo--container">
                <img class="nav__logo--image" src="../../assets/images/cogov__logo--purple.png" alt="">
                <p class="nav__logo--text">CoGov</p>            
            </div>        
        </a>
        <div class="nav__items">
            <div class="nav__item">
                <a href='/about' class="removelink">About</a>
            </div>
            <div class="nav__item">
                <a href='/holochain' class="removelink">Holochain</a>
            </div>
            <div class="nav__item">
                <a href='/whitepaper' class="removelink">Whitepaper</a>
            </div>
            <div class="nav__item">
                <a href='/connect' class="removelink">Connect</a>
            </div>
        </div>

    </div>
</template>
